<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 *
 * @category    design
 * @package     fw_default
 */

/** @var string $description */
$description = $this->getProduct()->getDescription();
?>
<?php if ($description): ?>
    <div class="std product-desc">
		<!--<input type="checkbox" id="read-more" role="button" />
		<label for="read-more"><span class="read-more">More Product Description</span><span class="read-less">Less Product Description</span></label>-->
		<!--<div class="exp">-->
			<div class="desc-wrapper">
				<?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $description, 'description') ?>
			</div>
		<!--</div>-->
    </div>
<?php endif; ?>