<?php
/**
 * @category    design
 * @package     fw_default
 */

/** @var Mage_Sales_Model_Quote_Item $item */
$item = $this->getItem();

/** @var Mage_Core_Model_Product $product */
$product = $item->getProduct();

$isVisibleProduct = $product->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($product, Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item" xmlns="http://www.w3.org/1999/html">
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details">
        <p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->escapeHtml($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
        <table class="info-wrapper">
            <tbody>
                <tr>
                    <th><?php echo $this->__('Price'); ?></th>
                    <td>
                        <?php if ($canApplyMsrp): ?>
                            <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
                        <?php else: ?>
                            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                    <?php echo $this->__('Excl. Tax'); ?>:
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales')): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()) ?>
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->getApplied($item)): ?>
                                    <br />
                                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
                                            <?php endforeach; ?>
                                        </small>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales')): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php endif; ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales')): ?>
                                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($item->getCalculationPrice()+$item->getWeeeTaxAppliedAmount()+$item->getWeeeTaxDisposition()); ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                                <?php $_incl = $this->helper('checkout')->getPriceInclTax($item); ?>
                                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                                    <br /><?php echo $this->__('Incl. Tax'); ?>:
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($item, array(0, 1, 4), 'sales')): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($item)); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_incl-$item->getWeeeTaxDisposition()) ?>
                                <?php endif; ?>
                                <?php if (Mage::helper('weee')->getApplied($item)): ?>
                                    <br />
                                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 1, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales')): ?>
                                        <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span>
                                        <?php endforeach; ?>
                                    <?php elseif (Mage::helper('weee')->typeOfDisplay($item, 4, 'sales')): ?>
                                        <small>
                                            <?php foreach (Mage::helper('weee')->getApplied($item) as $tax): ?>
                                                <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                                            <?php endforeach; ?>
                                        </small>
                                    <?php endif; ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($item, 2, 'sales')): ?>
                                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($item)); ?></span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                        <?php endif; //Can apply MSRP ?>
                    </td>
                </tr>
                <tr class="qty-wrapper<?php if($item->getSoldByLength()) echo ' soldbylength' ?>">
                    <th><?php echo $this->__('Qty'); ?></th>
                    <td>
                        <?php if($item->getSoldByLength() == 1): ?>
                            <?php
                            /** @var Mage_CatalogInventory_Model_Stock_Item $stockItem */
                            $stockItem = $product->getStockItem();
                            ?>
                            <input
                                type="hidden"
                                id="qinput-<?php echo $item->getId(); ?>"
                                data-link="<?php echo $this->getAjaxUpdateUrl() ?>"
                                data-item-id="<?php echo $item->getId(); ?>"
                                data-cart-item-id="<?php echo $item->getSku(); ?>"
                                class="qty cart-item-quantity input-text" name=""
                                value="<?php echo $this->getQty()?>"
                                <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
                                />
                            <div class="qty-whole">
                                <?php $w = floor($this->getQty() / 8) ?>
                                <select name="qty-whole">
                                    <?php for ($i = 0; $i <= 20; $i++): ?>
                                        <option value="<?php echo $i ?>"<?php if ($w == $i) echo " selected" ?>>
                                            <?php echo $i ?>
                                        </option>
                                    <?php endfor ?>
                                </select>
                                <label for="qty-whole"><?php echo $this->__('Whole') ?></label>
                            </div>
                            <div class="qty-fraction">
                                <?php $f = $this->getQty() % 8; ?>
                                <select name="qty-fraction">
                                    <?php $incrementBy = $stockItem->getEnableQtyIncrements() ? $stockItem->getQtyIncrements() : 1 ?>
                                    <?php for ($i = 0; $i < 8; $i = $i + $incrementBy): ?>
                                        <option value="<?php echo $i ?>"<?php if ($f == $i) echo " selected" ?>>
                                            <?php echo $i ? Mage::helper('fw_soldbylength')->getFraction($i) : '--' ?>
                                        </option>
                                    <?php endfor ?>
                                </select>
                                <label for="qty-fraction"><?php echo $this->__('Fraction') ?></label>
                            </div>
                            Yards
                        <?php else: ?>
                            <input
                                id="qinput-<?php echo $item->getId(); ?>"
                                data-link="<?php echo $this->getAjaxUpdateUrl() ?>"
                                data-item-id="<?php echo $item->getId(); ?>"
                                data-cart-item-id="<?php echo $item->getSku(); ?>"
                                class="qty cart-item-quantity input-text" name=""
                                value="<?php echo $this->getQty()?>"
                                <?php if ($this->isOnCheckoutPage()) echo 'disabled'; ?>
                                />
                        <?php endif ?>
                        <button id="qbutton-<?php echo $item->getId(); ?>"
                                data-item-id="<?php echo $item->getId(); ?>"
                                disabled="disabled"
                                data-update
                                data-cart-item-update
                                class="button quantity-button">
                            <?php echo $this->__('ok'); ?>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

        <?php if ($isVisibleProduct): ?>
        <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Edit item')) ?>" class="btn-edit">
            <?php echo $this->__('Edit item')?>
        </a>
            |
            <?php if (!$this->isOnCheckoutPage()): ?>
                <a href="<?php echo $this->getAjaxDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>"
                   data-confirm="<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>"
                   class="remove">
                    <?php echo $this->__('Remove Item') ?>
                </a>
            <?php else: ?>
                <span><?php echo $this->__('Remove Item') ?></span>
            <?php endif; ?>
        <?php endif ?>



        <?php if ($_options = $this->getOptionList()):?>
        <div class="truncated">
          <div class="truncated_full_value">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd>
                    <?php if (is_array($_option['value'])): ?>
                    <?php echo nl2br(implode("\n", $_option['value'])) ?>
                    <?php else: ?>
                    <?php echo $_option['value'] ?>
                    <?php endif; ?>
                </dd>
                <?php endforeach; ?>
            </dl>
          </div>
        <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
        </div>
        <?php endif; ?>

    </div>
</li>
