<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 *
 * @category    design
 * @package     fw_default
 */

/** @var Mage_Core_Model_Product $product */
$product = $this->getProduct();

/** @var Mage_Catalog_Helper_Output $_helper */
$_helper = $this->helper('catalog/output');
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view" itemscope itemtype="http://schema.org/Product">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-img-box">
                <div class="product-name">
                    <h1 itemprop="name"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></h1>
                </div>
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="product-description" itemprop="description">
                <div class="product-name">
                    <span class="h1"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></span>
                </div>
                <?php echo $this->getChildHtml('description') ?>
                <?php echo $this->getChildHtml('additional') ?>
            </div>

            <?php if ($sku = $product->getSku()): ?>
                <meta itemprop="productID" content="sku:<?php echo $sku; ?>" />
            <?php endif; ?>

            <div class="product-shop" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                <div class="price-info">
                    <?php echo $this->getPriceHtml($product); ?>
                    <?php echo $this->getChildHtml('bundle_prices') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                </div>

                <div class="extra-info">
                    <?php echo $this->getChildHtml('product_type_availability'); ?>
                    <?php if($product->isGrouped()): ?>
                        <p class="grouped-notice"><?php echo $this->__('Select Quantity and Colors below and then Add to Cart') ?></p>
                    <?php endif; ?>
                </div>

                <meta itemprop="itemCondition" itemtype="http://schema.org/OfferItemCondition" content="New" />

                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('other');?>

                <?php if ($product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

            </div>

            <div class="add-to-cart-wrapper">
                <?php echo $this->getChildHtml('extrahint') ?>

                <?php if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($product->isSaleable()): ?>
                            <?php if(!$product->isGrouped()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($product)): ?>
                                <span class="or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php // echo $this->getChildHtml('sharing') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php elseif (!$product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                        <?php // echo $this->getChildHtml('sharing') ?>
                    </div>
                <?php endif; ?>
            </div>

            <?php echo $this->getChildHtml('related_products') ?>

            <div class="clearer"></div>
            <?php if ($product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

            <?php $reviewSummary = $this->getReviewsSummaryHtml($product, 'default', false); ?>
            <?php $productReviewExcerpt = $this->getChildHtml('product_review_excerpt'); ?>
            <?php if ($reviewSummary && $productReviewExcerpt && !$product->isGrouped()) : ?>
                <div class="review-excerpt-container">
                    <?php echo $reviewSummary; ?>
                    <?php echo $productReviewExcerpt; ?>
                </div>
            <?php else : ?>
                <div class="reviews-callout">
                    <?php echo $productReviewExcerpt; ?>
                </div>
            <?php endif; ?>

            <?php echo $this->getChildHtml('product_type_data') ?>

            <?php if($product->isGrouped()): ?>
                <div class="grouped-addtocart"><?php echo $this->getChildHtml('addtocart') ?></div>
            <?php endif; ?>

        </form>
        <script type="text/javascript">
            //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('igdrec_1') ?>
    <div class="product-reviews">
        <?php echo $this->getChildHtml('reviews') ?>
    </div>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
