<?php
/**
 * @category    design
 * @package     fw_default
 */
?>
<?php $_product = $this->getProduct() ?>
<?php $_finalPrice = $_product->getFinalPrice() ?>
<?php $_finalPriceInclTax = $_product->getFinalPrice() ?>
<?php $_weeeTaxAmount = 0; ?>
<?php
if ($_product->getPriceType() == 1) {
    $_weeeTaxAmount = Mage::helper('weee')->getAmount($_product);
    if (Mage::helper('weee')->typeOfDisplay($_product, array(1,2,4))) {
        $_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForRenderer($_product);
    }
}
$isMAPTypeOnGesture = Mage::helper('catalog')->isShowPriceOnGesture($_product);
$canApplyMAP  = Mage::helper('catalog')->canApplyMsrp($_product);
?>